version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: pg-local
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: [ "5432:5432" ]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "app" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  redis_data:
  pg_data:
